# Copyright © 2018–2019 Trevor Spiteri

# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved. This file is offered as-is,
# without any warranty.

skip_tags: true

environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: i686-pc-windows-msvc
    - TARGET: i686-pc-windows-gnu

cache:
  - '%USERPROFILE%\.cargo\registry\cache -> Cargo.toml'

install:
  - set PATH=%USERPROFILE%\.cargo\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain none --no-modify-path
  - rustup --version
  - rustup install beta-%TARGET% 1.39.0-%TARGET%
  - rustup component add --toolchain beta-%TARGET% rustfmt clippy

build: false

before_test:
  - C:\msys64\usr\bin\bash -c "if [ -d ""$USERPROFILE/.cargo/registry/cache"" ]; then cd ""$USERPROFILE/.cargo/registry""; /c/msys64/usr/bin/find cache -name \*.crate; fi"

test_script:
  - cargo +beta-%TARGET% clippy --all-targets --features "fail-on-warnings az f16 serde std"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings az f16 serde"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings az f16 std"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings az f16"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings az serde std"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings az serde"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings az std"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings az"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings az"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings f16 serde std"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings f16 serde"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings f16 std"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings f16"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings serde std"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings serde"
  - cargo +beta-%TARGET% check --all-targets --features "fail-on-warnings std"
  - cargo +beta-%TARGET% check --all-targets --features fail-on-warnings
  - cargo +beta-%TARGET% test --release --features "fail-on-warnings az f16 serde"
  - cargo +beta-%TARGET% fmt -- --check
  - cargo +1.39.0-%TARGET% test --lib --features "fail-on-warnings az f16 serde"

after_test:
  - C:\msys64\usr\bin\bash -c "if [ -d ""$USERPROFILE/.cargo/registry/cache"" ]; then cd ""$USERPROFILE/.cargo/registry""; /c/msys64/usr/bin/find cache -name \*.crate; fi"
