# Copyright © 2018–2020 Trevor Spiteri

# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved. This file is offered as-is,
# without any warranty.

[package]
name = "fixed"
version = "1.2.0"
authors = ["Trevor Spiteri <tspiteri@ieee.org>"]
description = "Fixed-point numbers"
documentation = "https://docs.rs/fixed"
repository = "https://gitlab.com/tspiteri/fixed"
readme = "README.md"
keywords = ["mathematics", "numerics"]
categories = ["algorithms", "data-structures", "no-std", "science"]
license = "MIT/Apache-2.0"
edition = "2018"
autobenches = false

[features]
f16 = ["half"]
fail-on-warnings = []
std = []
unwrapped = []
serde-str = ["serde", "std"]

[dependencies]
typenum = "1.10"
az = { version = "1", optional = true }
half = { version = "1.6", optional = true }
num-traits = { version = "0.2.12", default-features = false, optional = true }
serde = { version = "1.0.60", default-features = false, optional = true }

[dev-dependencies]
rand = { version = "0.7", default-features = false }
rand_xoshiro = "0.4"
criterion = "0.3"
num-traits = { version = "0.2", default-features = false }

[package.metadata.docs.rs]
features = ["az", "f16", "num-traits", "serde", "std", "unwrapped"]

[[bench]]
name = "bench_main"
harness = false
